version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialdb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npx prisma generate && sleep 3 && npx prisma migrate deploy && npm run dev"
    environment:
      - PORT=4001
      - JWT_SECRET=dev_secret
      - JWT_EXPIRES_IN=3600
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/socialdb?schema=public
      - NODE_ENV=development
    volumes:
      - ./:/app
    ports:
      - '4001:4001'
    depends_on:
      - db

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host --port 8080"
    environment:
      - VITE_API_URL=http://localhost:4001
      - NODE_ENV=development
    volumes:
      - ../connect-circle-93:/app
    ports:
      - '8080:8080'
    depends_on:
      - backend

volumes:
  db_data:
